import numpy as np


def print_results(acc: float | np.ndarray, model: object) -> None:
    """
    Print a summary of model performance and scoring thresholds.

    Parameters
    ----------
    acc : float
        Classification accuracy of the model.
    scores : list or np.ndarray
        Predicted credit scores generated by the model.
    model : object
        Trained scoring model containing the threshold attributes `t1` and `t2`.
    """
    print("Accuracy:", acc)
    print(f"Thresholds used → t1: {model.t1}, t2: {model.t2}")
